name: Preflight Release Check

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release-dry-run:
    name: Dry-Run Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure npm for authentication
        run: echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run release-it in dry-run mode
        run: npm publish --dry-run --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
